/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import myapp.entity.Motorcycle;
import javax.persistence.Persistence;
import javax.persistence.EntityManager;

public class App {
    public void start() {
		EntityManager em = Persistence.createEntityManagerFactory("myPersistence").createEntityManager();
		em.getTransaction().begin();

		Motorcycle en = new Motorcycle();
		en.setName("Winner");
		en.setVolume(149L);
		en.setFrontBrake("Plate Brake");
		en.setEngineType("DOHC");

		em.persist(en);

		em.getTransaction().commit();
		em.close();
    }

    public static void main(String[] args) {
		new App().start();
    }
}
